[I 2024-12-04 17:21:18,416] Using an existing study with name 'Tc_xgb' instead of creating a new one.
[I 2024-12-04 17:21:25,357] Trial 385 finished with value: 0.2521414482624318 and parameters: {'n_estimators': 1447, 'max_depth': 3, 'learning_rate': 0.06819895706117568, 'subsample': 0.7589371116984399, 'colsample_bytree': 0.5736744938056588, 'min_child_weight': 1, 'gamma': 2.20127667650379e-05, 'reg_alpha': 0.00014876367801050998, 'reg_lambda': 8.12884472829763e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:30,863] Trial 386 finished with value: 0.2554436860447201 and parameters: {'n_estimators': 1272, 'max_depth': 3, 'learning_rate': 0.08112697706801415, 'subsample': 0.7342687878545963, 'colsample_bytree': 0.6575820733152002, 'min_child_weight': 1, 'gamma': 2.3428161484472346e-05, 'reg_alpha': 4.499354392625762e-05, 'reg_lambda': 0.00021586526917899635}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:31,342] Trial 411 finished with value: 0.2508216051623922 and parameters: {'n_estimators': 1081, 'max_depth': 4, 'learning_rate': 0.09422733133383411, 'subsample': 0.7286461388573514, 'colsample_bytree': 0.6895805935283088, 'min_child_weight': 1, 'gamma': 1.955610959858224e-05, 'reg_alpha': 0.00021039187278872173, 'reg_lambda': 6.0420734744903686e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:33,783] Trial 402 finished with value: 0.254797906547114 and parameters: {'n_estimators': 1408, 'max_depth': 3, 'learning_rate': 0.06327212225676389, 'subsample': 0.7716154071423543, 'colsample_bytree': 0.5859546299833154, 'min_child_weight': 1, 'gamma': 0.00027375760131566476, 'reg_alpha': 7.307946256347431e-05, 'reg_lambda': 0.0006239447685569558}. Best is trial 276 with value: 0.22881696398411586.
[W 2024-12-04 17:21:33,913] Trial 415 failed with parameters: {'n_estimators': 1307, 'max_depth': 4, 'learning_rate': 0.06362901019696984} because of the following error: StorageInternalError('An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. ').
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (416, 'subsample', 0.7664249526529275, '{"name": "FloatDistribution", "attributes": {"step": null, "low": 0.7, "high": 1.0, "log": false}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 261, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 262, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 175, in <lambda>
    return lambda trial, name: trial.suggest_float(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 161, in suggest_float
    suggested_value = self._suggest(name, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
[W 2024-12-04 17:21:33,941] Trial 415 failed with value None.
[I 2024-12-04 17:21:34,028] Trial 413 finished with value: 0.25362949478939817 and parameters: {'n_estimators': 1224, 'max_depth': 4, 'learning_rate': 0.0752550898149872, 'subsample': 0.7119490558302236, 'colsample_bytree': 0.6596833279913757, 'min_child_weight': 1, 'gamma': 0.0006471022795780234, 'reg_alpha': 2.3313022373504472e-05, 'reg_lambda': 0.0002284452891830216}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:34,511] Trial 396 finished with value: 0.2584231786747765 and parameters: {'n_estimators': 1349, 'max_depth': 4, 'learning_rate': 0.07133481847795928, 'subsample': 0.7913577033980891, 'colsample_bytree': 0.6868800885681483, 'min_child_weight': 1, 'gamma': 1.8607199315226853e-05, 'reg_alpha': 0.00019389459200319984, 'reg_lambda': 0.0027112981574624155}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:34,837] Trial 407 finished with value: 0.2713958312720262 and parameters: {'n_estimators': 1322, 'max_depth': 3, 'learning_rate': 0.05312951778577841, 'subsample': 0.8101981570774219, 'colsample_bytree': 0.6820972016786305, 'min_child_weight': 1, 'gamma': 0.0007692336622325811, 'reg_alpha': 4.980604008817006e-05, 'reg_lambda': 0.0020044585952247364}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:35,035] Trial 387 finished with value: 0.2574114550060547 and parameters: {'n_estimators': 1172, 'max_depth': 3, 'learning_rate': 0.07745559960873881, 'subsample': 0.7221817732492918, 'colsample_bytree': 0.7035528194216127, 'min_child_weight': 1, 'gamma': 3.0344095295765338e-05, 'reg_alpha': 4.481618631414493e-05, 'reg_lambda': 0.0005292143828627598}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:35,429] Trial 416 finished with value: 0.26229870250423915 and parameters: {'n_estimators': 1336, 'max_depth': 4, 'learning_rate': 0.06822900585323001, 'subsample': 0.7328364843230216, 'colsample_bytree': 0.6355725435806765, 'min_child_weight': 1, 'gamma': 0.00015025692196226376, 'reg_alpha': 1.1211150600883445e-05, 'reg_lambda': 6.93813872763386e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:35,496] Trial 403 finished with value: 0.27647708330154086 and parameters: {'n_estimators': 1318, 'max_depth': 4, 'learning_rate': 0.06818585336838916, 'subsample': 0.7395315805479646, 'colsample_bytree': 0.5450863706740264, 'min_child_weight': 2, 'gamma': 8.517376902064329e-05, 'reg_alpha': 1.7861336170399898e-05, 'reg_lambda': 0.00019343587938562044}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:35,671] Trial 400 finished with value: 0.25951073091227445 and parameters: {'n_estimators': 1187, 'max_depth': 4, 'learning_rate': 0.08044577070305728, 'subsample': 0.7568642287617157, 'colsample_bytree': 0.6007530803920587, 'min_child_weight': 1, 'gamma': 9.796869524093254e-05, 'reg_alpha': 6.257865591433352e-05, 'reg_lambda': 0.008761097214763694}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:35,922] Trial 408 finished with value: 0.24487701804352774 and parameters: {'n_estimators': 1105, 'max_depth': 3, 'learning_rate': 0.09895533081028053, 'subsample': 0.7135881942076996, 'colsample_bytree': 0.5372782666248562, 'min_child_weight': 1, 'gamma': 5.424065404356245e-05, 'reg_alpha': 8.87930728291284e-05, 'reg_lambda': 0.00018459490209420045}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:36,879] Trial 405 finished with value: 0.24464183993036448 and parameters: {'n_estimators': 1060, 'max_depth': 4, 'learning_rate': 0.09119019264748285, 'subsample': 0.7261219369896894, 'colsample_bytree': 0.5806866259903922, 'min_child_weight': 1, 'gamma': 0.0009010852579987491, 'reg_alpha': 0.0001673305314723774, 'reg_lambda': 0.0009861532071882995}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:36,977] Trial 414 finished with value: 0.25458624635565397 and parameters: {'n_estimators': 1301, 'max_depth': 4, 'learning_rate': 0.08288732043607701, 'subsample': 0.7432910610857408, 'colsample_bytree': 0.6714509144250509, 'min_child_weight': 1, 'gamma': 4.166088411509622e-05, 'reg_alpha': 4.24341883952494e-05, 'reg_lambda': 0.0006262993511067029}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:37,002] Trial 392 finished with value: 0.2525423051187939 and parameters: {'n_estimators': 1211, 'max_depth': 3, 'learning_rate': 0.07455756859329317, 'subsample': 0.7510311383937951, 'colsample_bytree': 0.6273159918419331, 'min_child_weight': 1, 'gamma': 0.00013823112484479121, 'reg_alpha': 2.855784501063866e-05, 'reg_lambda': 3.101958740428221e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:37,088] Trial 410 finished with value: 0.2475304157615416 and parameters: {'n_estimators': 1167, 'max_depth': 3, 'learning_rate': 0.08357176244127244, 'subsample': 0.7678598302658397, 'colsample_bytree': 0.5889732315033871, 'min_child_weight': 1, 'gamma': 8.854251582587467e-05, 'reg_alpha': 0.00010505982309481165, 'reg_lambda': 4.494058776429515e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:37,358] Trial 404 finished with value: 0.26431903156841563 and parameters: {'n_estimators': 1344, 'max_depth': 4, 'learning_rate': 0.09691798663391701, 'subsample': 0.7654990867338269, 'colsample_bytree': 0.5901456667261297, 'min_child_weight': 2, 'gamma': 4.0080186207143606e-05, 'reg_alpha': 0.00010661627935995304, 'reg_lambda': 0.0005671126032080727}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:37,491] Trial 401 finished with value: 0.2676082037498525 and parameters: {'n_estimators': 882, 'max_depth': 5, 'learning_rate': 0.07420706172962993, 'subsample': 0.7481741143701224, 'colsample_bytree': 0.567979205414622, 'min_child_weight': 1, 'gamma': 0.000132619276247016, 'reg_alpha': 2.355591132007958e-05, 'reg_lambda': 0.00033898556893088437}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:38,029] Trial 406 finished with value: 0.26594712987855423 and parameters: {'n_estimators': 1355, 'max_depth': 3, 'learning_rate': 0.05976875410325173, 'subsample': 0.7460037057585748, 'colsample_bytree': 0.6485956505007899, 'min_child_weight': 1, 'gamma': 0.00017918277623322937, 'reg_alpha': 4.5405623541203076e-05, 'reg_lambda': 0.0018659442345368934}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:38,182] Trial 388 finished with value: 0.24974560491866554 and parameters: {'n_estimators': 1279, 'max_depth': 3, 'learning_rate': 0.0744441607347375, 'subsample': 0.8078505148366372, 'colsample_bytree': 0.5795972244969559, 'min_child_weight': 1, 'gamma': 0.0003070468700537147, 'reg_alpha': 0.0002894104773485386, 'reg_lambda': 0.00023594043597710822}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:38,198] Trial 389 finished with value: 0.23364123494832084 and parameters: {'n_estimators': 1366, 'max_depth': 3, 'learning_rate': 0.09651208088485916, 'subsample': 0.7235959562392509, 'colsample_bytree': 0.5869589325715749, 'min_child_weight': 1, 'gamma': 1.3265391886945603e-05, 'reg_alpha': 6.201431550994782e-05, 'reg_lambda': 3.0087029857148622e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:38,279] Trial 398 finished with value: 0.2704021608303731 and parameters: {'n_estimators': 1258, 'max_depth': 4, 'learning_rate': 0.09507363821074981, 'subsample': 0.7723937063931263, 'colsample_bytree': 0.5687190872513641, 'min_child_weight': 2, 'gamma': 0.00021225326524200295, 'reg_alpha': 0.0001770440008232051, 'reg_lambda': 0.0001992245799377323}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:38,740] Trial 397 finished with value: 0.2565797757218812 and parameters: {'n_estimators': 1288, 'max_depth': 4, 'learning_rate': 0.08139758445350893, 'subsample': 0.7413661490058587, 'colsample_bytree': 0.5903082267813293, 'min_child_weight': 1, 'gamma': 0.00024164797065860346, 'reg_alpha': 1.5670867399122046e-05, 'reg_lambda': 0.00022821247598316888}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:38,773] Trial 393 finished with value: 0.24843985291874415 and parameters: {'n_estimators': 1383, 'max_depth': 3, 'learning_rate': 0.09645797819125981, 'subsample': 0.7592682293573647, 'colsample_bytree': 0.6581456460729042, 'min_child_weight': 1, 'gamma': 0.0006268134970751864, 'reg_alpha': 2.50112994240602e-05, 'reg_lambda': 9.085679889643338e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:39,055] Trial 409 finished with value: 0.2595163483147833 and parameters: {'n_estimators': 1272, 'max_depth': 3, 'learning_rate': 0.061592821272502006, 'subsample': 0.765633027214256, 'colsample_bytree': 0.654517357757173, 'min_child_weight': 1, 'gamma': 2.5045636822963955e-05, 'reg_alpha': 0.00012186678278230478, 'reg_lambda': 3.1879644647540824e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:39,460] Trial 395 finished with value: 0.2511045628567817 and parameters: {'n_estimators': 1237, 'max_depth': 4, 'learning_rate': 0.08698129111901973, 'subsample': 0.7053538389570628, 'colsample_bytree': 0.6262460275893549, 'min_child_weight': 1, 'gamma': 0.00022483291849574442, 'reg_alpha': 6.046714883416753e-05, 'reg_lambda': 0.0001125469842132724}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:39,588] Trial 399 finished with value: 0.2526138051013484 and parameters: {'n_estimators': 1236, 'max_depth': 4, 'learning_rate': 0.08738291292288397, 'subsample': 0.7326118391731257, 'colsample_bytree': 0.5959601246224471, 'min_child_weight': 1, 'gamma': 4.996672279547243e-05, 'reg_alpha': 1.427993628253576e-05, 'reg_lambda': 0.0008066708496259828}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:39,732] Trial 417 finished with value: 0.25600888101545466 and parameters: {'n_estimators': 1324, 'max_depth': 4, 'learning_rate': 0.08277843022891603, 'subsample': 0.7161719768374655, 'colsample_bytree': 0.5343313404125589, 'min_child_weight': 1, 'gamma': 0.00023590420779155018, 'reg_alpha': 0.0001283566782220473, 'reg_lambda': 0.00011325574686614961}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:39,898] Trial 391 finished with value: 0.24949600470260525 and parameters: {'n_estimators': 1340, 'max_depth': 3, 'learning_rate': 0.08933243415253234, 'subsample': 0.7491366598596885, 'colsample_bytree': 0.6338727893638182, 'min_child_weight': 1, 'gamma': 0.0002354061185564201, 'reg_alpha': 0.00015229905378216565, 'reg_lambda': 0.0001806864917323919}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:40,197] Trial 394 finished with value: 0.24676168787156835 and parameters: {'n_estimators': 1342, 'max_depth': 3, 'learning_rate': 0.08002137403897484, 'subsample': 0.7351170869033942, 'colsample_bytree': 0.5980657783122066, 'min_child_weight': 1, 'gamma': 1.0786641974404e-05, 'reg_alpha': 0.00010389776983700779, 'reg_lambda': 7.009729066245416e-05}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:40,561] Trial 390 finished with value: 0.280623465565663 and parameters: {'n_estimators': 1275, 'max_depth': 5, 'learning_rate': 0.08137548377530857, 'subsample': 0.7658700810139143, 'colsample_bytree': 0.5815935777563259, 'min_child_weight': 2, 'gamma': 1.5983905624155697e-05, 'reg_alpha': 0.00024495059394438534, 'reg_lambda': 0.0006685968001121046}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:40,586] Trial 412 finished with value: 0.2422695536929332 and parameters: {'n_estimators': 1455, 'max_depth': 3, 'learning_rate': 0.08143856980505984, 'subsample': 0.7720875367431392, 'colsample_bytree': 0.5973358168854142, 'min_child_weight': 1, 'gamma': 0.0001780278634323712, 'reg_alpha': 0.0003766533765739858, 'reg_lambda': 0.0006462924427053859}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:40,708] Trial 419 finished with value: 0.2439334114080978 and parameters: {'n_estimators': 1351, 'max_depth': 3, 'learning_rate': 0.09843447351450337, 'subsample': 0.7343239171392485, 'colsample_bytree': 0.5656972351992064, 'min_child_weight': 1, 'gamma': 0.00011969080430400014, 'reg_alpha': 0.00015206851298981252, 'reg_lambda': 0.00015865028617509017}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:40,832] Trial 420 finished with value: 0.2471958447284064 and parameters: {'n_estimators': 1139, 'max_depth': 3, 'learning_rate': 0.09994730697875417, 'subsample': 0.7584884145250328, 'colsample_bytree': 0.5322572153803757, 'min_child_weight': 1, 'gamma': 0.019073512620926974, 'reg_alpha': 0.00010556016034556696, 'reg_lambda': 0.0001975274110075193}. Best is trial 276 with value: 0.22881696398411586.
[I 2024-12-04 17:21:41,051] Trial 418 finished with value: 0.2554753190176509 and parameters: {'n_estimators': 1140, 'max_depth': 4, 'learning_rate': 0.08808172527109541, 'subsample': 0.7290708677594909, 'colsample_bytree': 0.6605170657757686, 'min_child_weight': 1, 'gamma': 0.00022243857257514275, 'reg_alpha': 4.270368689319127e-05, 'reg_lambda': 0.0001399701316278444}. Best is trial 276 with value: 0.22881696398411586.
Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 81, in _create_scoped_session
    session.commit()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2028, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4352, in flush
    self._flush(objects)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4488, in _flush
    transaction.rollback(_capture_exception=True)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4448, in _flush
    flush_context.execute()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO trial_params (trial_id, param_name, param_value, distribution_json) VALUES (?, ?, ?, ?)]
[parameters: (416, 'subsample', 0.7664249526529275, '{"name": "FloatDistribution", "attributes": {"step": null, "low": 0.7, "high": 1.0, "log": false}}')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/zhome/b1/0/88900/Documents/fair_gc/gc_ml.py", line 79, in <module>
    study, best_model = create_hyperparameter_optimizer(
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 294, in create_hyperparameter_optimizer
    study.optimize(objective, n_trials=n_trials, n_jobs=n_jobs)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/study.py", line 475, in optimize
    _optimize(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 100, in _optimize
    f.result()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 160, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 248, in _run_trial
    raise func_err
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/study/_optimize.py", line 197, in _run_trial
    value_or_values = func(trial)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 261, in objective
    params = {
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 262, in <dictcomp>
    name: suggest_fn(trial, name)
  File "/zhome/b1/0/88900/Documents/fair_gc/src/optims.py", line 175, in <lambda>
    return lambda trial, name: trial.suggest_float(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 161, in suggest_float
    suggested_value = self._suggest(name, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/trial/_trial.py", line 637, in _suggest
    storage.set_trial_param(trial_id, name, param_value_in_internal_repr, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_cached_storage.py", line 171, in set_trial_param
    self._backend.set_trial_param(trial_id, param_name, param_value_internal, distribution)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 585, in set_trial_param
    self._set_trial_param_without_commit(
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/optuna/storages/_rdb/storage.py", line 98, in _create_scoped_session
    raise optuna.exceptions.StorageInternalError(message) from e
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
