Seed set to 42
[I 2024-12-15 18:08:02,112] Using an existing study with name 'Omega_afp' instead of creating a new one.
Traceback (most recent call last):
  File "/zhome/b1/0/88900/Documents/fair_gc/optuna_gnn.py", line 75, in <module>
    study, best_model, train_params, model_config = afp_hyperparameter_optimizer(
  File "/zhome/b1/0/88900/Documents/fair_gc/src/gnn_hyperopt.py", line 344, in afp_hyperparameter_optimizer
    checkpoint = torch.load(best_trial.user_attrs['best_state_dict_path'])
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 986, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 435, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/zhome/b1/0/88900/miniconda3/envs/critprops/lib/python3.9/site-packages/torch/serialization.py", line 416, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/Omega_trial_2056_best_state.pt'
